### PR TITLE
Create harbour-ostos-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,
Thanks for the nice app! Here's Swedish translation if wanted.

eson

### CODE REVIEW

**Comment by alketola** [comment]
Excellent, I didn't dare to do it in Swedish myself, much better as done by a native!

**Comment by eson57** [comment]
You are right, Google translate has yet a long way to go.

**Comment by alketola** [comment]
Jag kan nog lite svenska, men jag no orkade göra det till. Grattis! :-D 

I Merged it but I you'll have to wait a little,  the next version in the Jolla shop will be in late August perhaps.

**Comment by eson57** [comment]
No problem! My qm file is working fine already.  :)

**Pull request merged**
